import type { UserRole } from "@/constants/roles";
import { USER_ROLES } from "@/constants/roles";

import {
  ALL_PERMISSIONS,
  PERMISSIONS,
  type Permission,
} from "./permissions";

const READ_PERMISSIONS: Permission[] = [
  PERMISSIONS.identity.read,
  PERMISSIONS.customers.read,
  PERMISSIONS.suppliers.read,
  PERMISSIONS.warehouses.read,
  PERMISSIONS.products.read,
  PERMISSIONS.catalog.read,
  PERMISSIONS.inventory.read,
  PERMISSIONS.stockMovements.read,
  PERMISSIONS.purchaseOrders.read,
  PERMISSIONS.rentalOrders.read,
  PERMISSIONS.dispatches.read,
  PERMISSIONS.returns.read,
  PERMISSIONS.repairs.read,
  PERMISSIONS.maintenances.read,
  PERMISSIONS.rentalInvoices.read,
  PERMISSIONS.payments.read,
  PERMISSIONS.accounts.read,
  PERMISSIONS.journalEntries.read,
  PERMISSIONS.financialReports.read,
  PERMISSIONS.reports.read,
  PERMISSIONS.assets.read,
  PERMISSIONS.assetCategories.read,
  PERMISSIONS.expenses.read,
  PERMISSIONS.settings.read,
  PERMISSIONS.sequences.read,
  PERMISSIONS.audit.read,
  PERMISSIONS.notifications.read,
  PERMISSIONS.dashboard.read,
  PERMISSIONS.dashboard.update,
];

const MANAGER_PERMISSIONS: Permission[] = ALL_PERMISSIONS.filter(
  (permission) => permission !== PERMISSIONS.settings.update,
);

const WORKER_PERMISSIONS: Permission[] = [
  PERMISSIONS.customers.read,
  PERMISSIONS.suppliers.read,
  PERMISSIONS.warehouses.read,
  PERMISSIONS.products.read,
  PERMISSIONS.catalog.read,
  PERMISSIONS.inventory.read,
  PERMISSIONS.stockMovements.read,
  PERMISSIONS.inventory.update,
  PERMISSIONS.inventory.adjust,
  PERMISSIONS.stockMovements.create,
  PERMISSIONS.purchaseOrders.read,
  PERMISSIONS.purchaseOrders.receive,
  PERMISSIONS.rentalOrders.read,
  PERMISSIONS.rentalOrders.reserve,
  PERMISSIONS.dispatches.read,
  PERMISSIONS.dispatches.create,
  PERMISSIONS.dispatches.update,
  PERMISSIONS.dispatches.complete,
  PERMISSIONS.dispatches.cancel,
  PERMISSIONS.returns.read,
  PERMISSIONS.returns.create,
  PERMISSIONS.returns.update,
  PERMISSIONS.returns.receive,
  PERMISSIONS.returns.inspect,
  PERMISSIONS.returns.complete,
  PERMISSIONS.returns.cancel,
  PERMISSIONS.repairs.read,
  PERMISSIONS.repairs.create,
  PERMISSIONS.repairs.update,
  PERMISSIONS.repairs.start,
  PERMISSIONS.repairs.complete,
  PERMISSIONS.repairs.cancel,
  PERMISSIONS.maintenances.read,
  PERMISSIONS.maintenances.create,
  PERMISSIONS.maintenances.update,
  PERMISSIONS.maintenances.start,
  PERMISSIONS.maintenances.complete,
  PERMISSIONS.maintenances.cancel,
  PERMISSIONS.rentalInvoices.read,
  PERMISSIONS.rentalInvoices.create,
  PERMISSIONS.rentalInvoices.update,
  PERMISSIONS.rentalInvoices.issue,
  PERMISSIONS.rentalInvoices.void,
  PERMISSIONS.payments.read,
  PERMISSIONS.payments.create,
  PERMISSIONS.payments.update,
  PERMISSIONS.payments.post,
  PERMISSIONS.payments.void,
  PERMISSIONS.notifications.read,
  PERMISSIONS.dashboard.read,
  PERMISSIONS.dashboard.update,
  PERMISSIONS.assets.read,
  PERMISSIONS.assets.create,
  PERMISSIONS.assets.update,
  PERMISSIONS.assets.transfer,
  PERMISSIONS.assets.dispose,
  PERMISSIONS.assets.maintenance,
  PERMISSIONS.assetCategories.read,
  PERMISSIONS.assetCategories.create,
  PERMISSIONS.assetCategories.update,
  PERMISSIONS.assetCategories.delete,
];

const ACCOUNTANT_PERMISSIONS: Permission[] = [
  ...READ_PERMISSIONS,
  PERMISSIONS.rentalInvoices.create,
  PERMISSIONS.rentalInvoices.update,
  PERMISSIONS.rentalInvoices.issue,
  PERMISSIONS.rentalInvoices.void,
  PERMISSIONS.payments.create,
  PERMISSIONS.payments.update,
  PERMISSIONS.payments.post,
  PERMISSIONS.payments.void,
  PERMISSIONS.accounts.read,
  PERMISSIONS.accounts.create,
  PERMISSIONS.accounts.update,
  PERMISSIONS.journalEntries.read,
  PERMISSIONS.journalEntries.create,
  PERMISSIONS.journalEntries.update,
  PERMISSIONS.journalEntries.post,
  PERMISSIONS.journalEntries.void,
  PERMISSIONS.expenses.create,
  PERMISSIONS.expenses.update,
  PERMISSIONS.expenses.approve,
  PERMISSIONS.expenses.reject,
  PERMISSIONS.expenses.pay,
  PERMISSIONS.assets.read,
  PERMISSIONS.assets.create,
  PERMISSIONS.assets.update,
  PERMISSIONS.assets.transfer,
  PERMISSIONS.assets.dispose,
  PERMISSIONS.assets.maintenance,
  PERMISSIONS.assetCategories.read,
  PERMISSIONS.assetCategories.create,
  PERMISSIONS.assetCategories.update,
  PERMISSIONS.assetCategories.delete,
];

export const ROLE_PERMISSIONS = {
  [USER_ROLES.OWNER]: ALL_PERMISSIONS,
  [USER_ROLES.MANAGER]: MANAGER_PERMISSIONS,
  [USER_ROLES.WORKER]: WORKER_PERMISSIONS,
  [USER_ROLES.ACCOUNTANT]: ACCOUNTANT_PERMISSIONS,
  [USER_ROLES.VIEWER]: READ_PERMISSIONS,
} as const satisfies Record<UserRole, readonly Permission[]>;
