export type {
  ActivityItem,
  ChartDataPoint,
  DashboardData,
  DashboardMetric,
  DashboardNotification,
  DashboardSummary,
  DashboardTrend,
  FinancialSummaryItem,
  InventoryOverviewItem,
  QuickAction,
  RentalTrendPoint,
  RevenueOverview,
  SystemStatusItem,
  UpcomingTask,
} from "./dashboard.types";
