import path from "node:path";
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: ["src/**/*.test.ts"],
    coverage: {
      provider: "v8",
      include: [
        "src/modules/customer/**/*.ts",
        "src/modules/supplier/**/*.ts",
        "src/modules/warehouse/**/*.ts",
        "src/modules/product/**/*.ts",
        "src/modules/inventory/**/*.ts",
        "src/modules/stock-movement/**/*.ts",
        "src/modules/procurement/**/*.ts",
        "src/modules/rental-order/**/*.ts",
        "src/modules/dispatch/**/*.ts",
        "src/modules/return/**/*.ts",
        "src/modules/repair/**/*.ts",
        "src/modules/maintenance/**/*.ts",
        "src/modules/rental-invoice/**/*.ts",
        "src/modules/payment/**/*.ts",
        "src/modules/accounting/**/*.ts",
        "src/modules/financial-report/**/*.ts",
        "src/modules/reporting/**/*.ts",
        "src/modules/identity/**/*.ts",
        "src/modules/asset/**/*.ts",
      ],
      exclude: [
        "src/modules/customer/**/*.test.ts",
        "src/modules/customer/tests/**",
        "src/modules/supplier/**/*.test.ts",
        "src/modules/supplier/tests/**",
        "src/modules/warehouse/**/*.test.ts",
        "src/modules/warehouse/tests/**",
        "src/modules/product/**/*.test.ts",
        "src/modules/product/tests/**",
        "src/modules/inventory/**/*.test.ts",
        "src/modules/inventory/tests/**",
        "src/modules/stock-movement/**/*.test.ts",
        "src/modules/stock-movement/tests/**",
        "src/modules/procurement/**/*.test.ts",
        "src/modules/procurement/tests/**",
        "src/modules/rental-order/**/*.test.ts",
        "src/modules/rental-order/tests/**",
        "src/modules/dispatch/**/*.test.ts",
        "src/modules/dispatch/tests/**",
        "src/modules/return/**/*.test.ts",
        "src/modules/return/tests/**",
        "src/modules/repair/**/*.test.ts",
        "src/modules/repair/tests/**",
        "src/modules/maintenance/**/*.test.ts",
        "src/modules/maintenance/tests/**",
        "src/modules/rental-invoice/**/*.test.ts",
        "src/modules/rental-invoice/tests/**",
        "src/modules/payment/**/*.test.ts",
        "src/modules/payment/tests/**",
        "src/modules/accounting/**/*.test.ts",
        "src/modules/accounting/tests/**",
        "src/modules/financial-report/**/*.test.ts",
        "src/modules/financial-report/tests/**",
        "src/modules/reporting/**/*.test.ts",
        "src/modules/reporting/tests/**",
        "src/modules/identity/**/*.test.ts",
        "src/modules/identity/tests/**",
        "src/modules/asset/**/*.test.ts",
        "src/modules/asset/tests/**",
      ],
    },
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
});
