export { mapPrismaError } from "./prisma-error-mapper";
export {
  createPrismaClient,
  getPrismaClient,
  prisma,
  default as defaultPrismaClient,
} from "./prisma-client";
export {
  checkDatabaseHealth,
  type DatabaseHealthResult,
} from "./database-health";
export type {
  DbClient,
  PrismaClient,
  TransactionClient,
} from "./prisma-types";
export {
  resolveDbClient,
  resolveDbClientFromContext,
  withPrismaError,
} from "./repository-base";
export {
  createRepositoryBase,
  createRepositoryBaseFromExecutionContext,
  createRepositoryBaseFromFullExecutionContext,
  createRepositoryBaseFromSharedDeps,
  createRepositoryRunner,
  createRepositoryRunnerFromExecutionContext,
  createRepositoryRunnerFromOptions,
  createRepositoryRunnerFromSharedDeps,
  createPrismaRepositoryBase,
  PrismaRepositoryBase,
  repositoryCount,
  repositoryCreate,
  repositoryDelete,
  repositoryFindFirst,
  repositoryFindMany,
  repositoryUpdate,
  buildPaginationMeta,
  buildPrismaSearchWhere,
  buildSearchWhereFromInput,
  composePrismaQuery,
  createRepositoryQuerySpec,
  executePagedQuery,
  mergePrismaWhere,
  normalizeSearchTerm,
  resolveSearchSpec,
  runRepositoryPagedQuery,
  createRepositoryUnitOfWork,
  createRepositoryUnitOfWorkContext,
  createRepositoryUnitOfWorkContextForTransaction,
  createTransactionScopedRepositoryContext,
  RepositoryUnitOfWork,
  runWithRepositoryUnitOfWork,
  runWithRepositoryUnitOfWorkFromExecutionContext,
  runWithUnitOfWorkRepositories,
  runWithUnitOfWorkRepositoriesFromExecutionContext,
  createObservableRepositoryRunner,
  createObservableRepositoryRunnerFromExecutionContext,
  createObservableRepositoryRunnerFromSharedDeps,
  createRepositoryObservationContextFromExecutionContext,
  createRepositoryObservationContextFromRequest,
  noopRepositoryMetrics,
  wrapRepositoryRunnerWithObservability,
  type CreateObservableRepositoryRunnerOptions,
  type IRepositoryMetrics,
  type IUnitOfWork,
  type ObservableRepositoryRunnerOptions,
  type RepositoryMetricsObservation,
  type RepositoryObservationContext,
  type RepositoryObservationMeta,
  type RepositoryUnitOfWorkContext,
  type UnitOfWorkOperation,
  type UnitOfWorkRepositoryFactory,
  type ComposedPrismaQuery,
  type ComposePrismaQueryOptions,
  type CreateRepositoryQuerySpecInput,
  type ExecutePagedQueryOptions,
  type PagedQueryArgs,
  type PagedQueryHandlers,
  type RepositoryBaseOptions,
  type RepositoryExecutionContext,
  type RepositoryFactoryOptions,
  type RepositoryOperationMeta,
  type RepositoryQuerySpec,
  type RepositoryRunner,
  type ResolvedSearchSpec,
  type RunRepositoryPagedQueryOptions,
  type SearchInput,
} from "./repository";
export {
  PrismaTransactionManager,
  type ITransactionManager,
} from "./transaction-manager";
